[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


[[redirects]]
  from = "/sentence/*"
  to = "https://sentencing-explained.netlify.app/:splat 200" 
  status = 200
  force = true


[[redirects]]
  from = "/pfa/*"
  to = "https://proxy-redirect-test.netlify.app/:splat 200" 
  status = 200
  force = true
